### Create a new user

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "tyra@email.com",
  "password": "test9393"
}


### sigin request
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "regis@email.com",
  "password": "test9393"
}


### Find a particular user with a  given Id
GET http://localhost:3000/auth/1


### Find all users with a given email
GET http://localhost:3000/auth?email=user1@email.com

### Set a colors
GET http://localhost:3000/auth/colors/blue


### get color
GET http://localhost:3000/auth/colors


### GET the currently signed in user
GET http://localhost:3000/auth/whoami


### SIGN GOUT

POST http://localhost:3000/auth/signout